name: Export Obsidian Vault to GitHub Pages

on:
  workflow_dispatch:

jobs:
  export-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output folder
        run: mkdir -p output

      - name: Run export with Docker
        run: |
          docker run --rm \
            --name obsidian-webpage-export \
            -v ./:/vault \
            -v ./output:/output \
            klaxalk/obsidian-webpage-export:1.9.0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
